#!name=中国移动去广告
#!desc=拦截中国移动部分广告及营销请求
#!author=Converted from Quantumult X
#!update=2026-09-28

[Rule]

# 广告服务器 IP
IP-CIDR,120.240.95.3732,REJECT

[URL Rewrite]

# 初始化接口
^httpsclient.app.coc.10086.cnbiz-orangeDNinitstartInit url REJECT

# 广告列表
^httpsclient.app.coc.10086.cnbiz-orangeDNexplorePagegetAdverList url REJECT

# 多个悬浮窗  营销内容
^https(client.app.cocapp).10086.cnbiz-orangeDNemotionMarket url REJECT

[MITM]

hostname = %APPEND% client.app.coc.10086.cn, app.10086.cn